language: go
go:
- 1.7
cache:
  directories:
  - vendor
install:
- go get -u github.com/Masterminds/glide
- glide install
script:
- go vet
- go test
before_deploy:
- GOOS=linux GOARCH=amd64 go build -o sapt_linux_amd64
- GOOS=darwin GOARCH=amd64 go build -o sapt_darwin_amd64
